"""Centralized trace context utilities for end-to-end request correlation.

This module provides the canonical identifiers for tracing:
- session_id: A conversational session initiated by a wake word
- turn_id: One user utterance that results in a response
- trace_id: Correlation ID for logs, IPC, and tool execution (MVP: equals turn_id)

Key rules:
- turn_id is generated by MicASRNode at VAD end (source of truth)
- trace_id == turn_id (MVP rule)
- Orchestrator must NOT generate its own turn_id
- Use contextvars for async-safe propagation (NOT thread-local)
- Any thread offloads must explicitly carry the TraceContext
"""

from contextvars import ContextVar, Token
from dataclasses import dataclass
from typing import Optional
import uuid


@dataclass
class TraceContext:
    """Canonical trace identifiers for a turn.

    Attributes:
        session_id: Session ID from wake word (sess_xxx) or fallback
        turn_id: Turn ID generated at VAD end (turn_xxx)
        trace_id: Correlation ID for logs/IPC (MVP: equals turn_id)
    """
    session_id: str
    turn_id: str
    trace_id: str  # MVP: equals turn_id

    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        return {
            "session_id": self.session_id,
            "turn_id": self.turn_id,
            "trace_id": self.trace_id,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "TraceContext":
        """Create from dictionary."""
        return cls(
            session_id=data.get("session_id", ""),
            turn_id=data.get("turn_id", ""),
            trace_id=data.get("trace_id", ""),
        )


# Async-safe context storage using ContextVar (NOT thread-local)
# Note: Any thread offloads (asyncio.to_thread, etc.) must explicitly
# carry the TraceContext - it does not auto-propagate across threads.
_trace_context: ContextVar[Optional[TraceContext]] = ContextVar(
    'trace_context',
    default=None
)


def set_trace_context(ctx: TraceContext) -> Token:
    """Set the current trace context and return a reset token.

    Call this at the start of request handling (e.g., MCP server on request receipt).
    Use reset_trace_context(token) to restore the previous context when done.

    Returns:
        Token for use with reset_trace_context()
    """
    return _trace_context.set(ctx)


def get_trace_context() -> Optional[TraceContext]:
    """Get the current trace context, or None if not set."""
    return _trace_context.get()


def clear_trace_context() -> None:
    """Clear the current trace context.

    Call this after request handling completes.
    Note: Prefer reset_trace_context(token) for proper context restoration.
    """
    _trace_context.set(None)


def reset_trace_context(token: Token) -> None:
    """Reset trace context to its previous value using the token.

    Args:
        token: Token returned by set_trace_context()
    """
    _trace_context.reset(token)


def trace_context_or_none() -> Optional[TraceContext]:
    """Alias for get_trace_context() for explicit null-safety."""
    return _trace_context.get()


def generate_session_id() -> str:
    """Generate a new session ID with sess_ prefix."""
    return f"sess_{uuid.uuid4().hex[:12]}"


def generate_turn_id() -> str:
    """Generate a new turn ID with turn_ prefix."""
    return f"turn_{uuid.uuid4().hex[:12]}"


# ROS message helpers
# frame_id semantics (hard rule):
# - Per-turn messages participating in the chain: header.frame_id = trace_id
# - Session-scoped events: header.frame_id must be empty; use JSON payload

def inject_trace_to_header(header, ctx: TraceContext) -> None:
    """Set header.frame_id = trace_id for turn-scoped messages only.

    Do NOT use this for session-scoped events (wake word, session_end).
    Those should leave frame_id empty and use JSON in data field.
    """
    header.frame_id = ctx.trace_id


def extract_trace_from_header(header) -> Optional[str]:
    """Extract trace_id from header.frame_id.

    Returns None if frame_id is empty or not set.
    """
    frame_id = getattr(header, 'frame_id', None)
    return frame_id if frame_id else None


# HTTP helpers

def trace_headers(ctx: TraceContext) -> dict:
    """Generate HTTP headers for trace propagation.

    Returns headers dict with:
    - X-Session-Id
    - X-Turn-Id
    - X-Trace-Id
    """
    return {
        "X-Session-Id": ctx.session_id,
        "X-Turn-Id": ctx.turn_id,
        "X-Trace-Id": ctx.trace_id,
    }


def extract_trace_from_http_headers(headers: dict) -> Optional[TraceContext]:
    """Extract trace context from HTTP request headers.

    Returns TraceContext if all three headers present, None otherwise.
    Caller should log missing_* fields if None.
    """
    session_id = headers.get("X-Session-Id") or headers.get("x-session-id")
    turn_id = headers.get("X-Turn-Id") or headers.get("x-turn-id")
    trace_id = headers.get("X-Trace-Id") or headers.get("x-trace-id")

    if session_id and turn_id and trace_id:
        return TraceContext(
            session_id=session_id,
            turn_id=turn_id,
            trace_id=trace_id,
        )
    return None


def missing_trace_fields(headers: dict) -> dict:
    """Return dict of missing trace header fields for logging.

    Use this to log which fields are absent when trace context is incomplete.
    """
    missing = {}
    if not (headers.get("X-Session-Id") or headers.get("x-session-id")):
        missing["missing_session_id"] = True
    if not (headers.get("X-Turn-Id") or headers.get("x-turn-id")):
        missing["missing_turn_id"] = True
    if not (headers.get("X-Trace-Id") or headers.get("x-trace-id")):
        missing["missing_trace_id"] = True
    return missing


# Logging helpers

def trace_log_fields(ctx: Optional[TraceContext]) -> dict:
    """Return dict of trace fields for structured logging.

    If ctx is None, returns missing_trace_context=True.
    """
    if ctx:
        return ctx.to_dict()
    return {"missing_trace_context": True}


def is_valid_turn_id(turn_id: str) -> bool:
    """Check if a string is a valid turn ID.

    Accepts both turn_ and utt_ prefixes for backward compatibility.
    """
    return turn_id.startswith("turn_") or turn_id.startswith("utt_")


def is_valid_session_id(session_id: str) -> bool:
    """Check if a string is a valid session ID."""
    return session_id.startswith("sess_")
